openapi: 3.0.0
info:
  title: Population anlysis API
  description: Analyse population based on geojson data.
  version: "1.0"
paths:
  /states:
    get:
      x-swagger-router-controller: main
      operationId: getStates
      tags:
        - /states
      description: >-
        Returns states.
      responses:
        "200":
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/States"
        default:
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /peoples:
    get:
      x-swagger-router-controller: main
      operationId: getPeoples
      tags:
        - /states
      description: >-
        Returns states.
      parameters:
        - in: query
          name: state_id
          schema:
            type: string
          required: true
          description: Alphanumeric character. State ID is used to filter records
      responses:
        "200":
          description: Successful request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Peoples"
        default:
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
servers:
  - url: "/api"
components:
  schemas:
    States:
      properties:
        states:
          type: array
      required:
        - states
    Peoples:
      properties:
        peoples:
          type: object
      required:
        - peoples
    Error:
      properties:
        message:
          type: string
      required:
        - message
